ALTER TABLE "Aluno" DROP CONSTRAINT "Aluno_duplaId_fkey";
ALTER TABLE "Aluno" ALTER COLUMN "duplaId" DROP NOT NULL;
ALTER TABLE "Aluno"
  ADD CONSTRAINT "Aluno_duplaId_fkey"
  FOREIGN KEY ("duplaId") REFERENCES "Dupla"("id") ON DELETE SET NULL ON UPDATE CASCADE;
